[options]
admin_passwd = admin

db_host = localhost
db_port = 5432
db_user = postgres
db_password = postgres

addons_path = C:\xampp\htdocs\odoo-emr\addons

logfile = C:\xampp\htdocs\odoo-emr\odoo.log

xmlrpc_port = 8069